# render.yaml

services:
  - name: fastapi-app
    type: web
    env:
      - key: DYNAMODB_ENDPOINT
        value: http://localstack:4566
      - key: S3_ENDPOINT
        value: http://localstack:4572
      - key: REDIS_HOST
        value: redis
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

  - name: celery-worker
    type: worker
    env:
      - key: REDIS_HOST
        value: redis
    startCommand: celery -A app.main.celery worker --loglevel=info
