# render.yaml

services:
  - name: fastapi-app
    type: web
    env:
      DYNAMODB_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4572
      REDIS_HOST: redis
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

  - name: celery-worker
    type: worker
    env:
      REDIS_HOST: redis
    startCommand: celery -A app.main.celery worker --loglevel=info
